# Generated by Django 6.1.1 on 2026-10-02 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='наименование')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('category', models.CharField(choices=[('massage', 'Massage'), ('moustache', 'Moustache'), ('beard', 'Beard'), ('haircut', 'Haircut')], default='haircut', max_length=50, verbose_name='категория')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='активна')),
                ('visit_time', models.DateTimeField(null=True, verbose_name='время записи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'бронирование мастера',
                'db_table': 'booking',
                'ordering': ['-created_at', '-price', 'category'],
            },
        ),
    ]
